CREATE USER C##BOOT IDENTIFIED BY BOOT;
GRANT CONNECT AND 

-- 사용자에게 세션 생성 권한 부여 (로그인 권한)
GRANT CREATE SESSION TO C##BOOT;

-- 사용자에게 테이블 생성 권한 부여
GRANT CREATE TABLE TO C##BOOT;

-- 사용자에게 임의의 다른 권한 부여 (예: SELECT ANY TABLE)
GRANT SELECT ANY TABLE TO C##BOOT;

-- 다른 필요한 권한도 동일하게 부여 가능
-- 예시: INSERT, UPDATE, DELETE 권한 등
-- GRANT INSERT ON table_name TO C##BOOT;
-- GRANT UPDATE ON table_name TO C##BOOT;
-- GRANT DELETE ON table_name TO C##BOOT;

-- CONNECT 권한 부여 (로그인 권한 포함)
GRANT CONNECT TO C##BOOT;

-- 추가 권한 부여 (예: 테이블 생성 권한)
GRANT CREATE TABLE TO C##BOOT;

-- 시스템 권한 부여 (예: SELECT ANY TABLE)
GRANT SELECT ANY TABLE TO C##BOOT;

GRANT CREATE SEQUENCE TO C##BOOT;

ALTER USER C##BOOT DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE ANY TABLE TO C##BOOT;
GRANT CONNECT, RESOURCE, DBA TO C##BOOT;

ALTER USER C##BOOT QUOTA 2M ON SYSTEM;